apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: nfd-controller-manager
  name: node-feature-discovery-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfd-controller-manager
  namespace: node-feature-discovery-operator
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: nfd-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: nfd-controller-manager
    spec:
      serviceAccountName: nfd-manager
      containers:
        - name: manager
          securityContext:
            runAsUser: 65534
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          command:
            - /node-feature-discovery-operator
          args:
            - --leader-elect
            - "--zap-encoder=console"
            - "--zap-log-level=debug"
          image: controller:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cluster-nfd-operator"
            - name: NODE_FEATURE_DISCOVERY_IMAGE
              value: "gcr.io/k8s-staging-nfd/node-feature-discovery:master"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      terminationGracePeriodSeconds: 10

